### ISSUE TITLE
Update for latest gitbucket version

### ISSUE THREAD

**Issue by mrmelon54** [alexandremenif/gitbucket-mirror-plugin#10]
Is it possible for you to update this plugin to work for the latest version of gitbucket or should I try that myself and send a PR?

**Comment by alexandremenif** [comment]
Hello, I am no longer using this plugin personnally, so I am not really interested in spending time working on it. Feel free to write a PR, I will review it. If you are motivated to maintain the plugin I can also add you as a contributor.

**Comment by mrmelon54** [comment]
I'll have a look into it
