### ISSUE TITLE
Premature EOF Error

### ISSUE THREAD

**Issue by jellykells** [alexandremenif/gitbucket-mirror-plugin#2]
I received the following error today after creating a new release:

> Error: https://jellykells@github.com/jellykells/uncomplicated-ssh-manager.git: Premature EOF

The accepted answer for [this question](https://stackoverflow.com/questions/12009493/git-push-fails-with-fatal-early-eof-when-pushing-but-only-on-one-file) on stackoverflow suggests disabling compression as a workaround, but I'm not sure if that's even possible for the plugin.

**Comment by jellykells** [comment]
I should add that I've recently updated to Gitbucket 4.30.1, so it may be some sort of compatibility issue.

**Comment by alexandremenif** [comment]
Hello @jellykells and thank you for submitting this issue.

If I understand correctly, you are having this error as a result when trying to mirror your repository?
Do you think that you could provide an example that I could use to reproduce the issue?

**Comment by jellykells** [comment]
Yes, it was working previously but now gives this error when attempting to mirror [this public repository](https://gitbucket.thisisjoes.site/joe/uncomplicated-ssh-manager) to [this one](https://github.com/jellykells/uncomplicated-ssh-manager) on Github.

I setup a personal access token on Github with public repo access, and the plugin is using that.
Gitbucket is also using an external MySQL db if that matters.

**Comment by alexandremenif** [comment]
Hello @jellykells,

Unfortunately I cannot reproduce your issue. I used the same version of Gitbucket as you did, although with an H2 database.

Do you think you could provide the logs produced by Gitbucket while you are having the error? Maybe it could help.

Also, maybe try to commit your change manually to the github repository, it may fix the issue. Or simply recreate a new mirror on github.

**Comment by jellykells** [comment]
I couldn't find the Gitbucket logs on my installation, however, after manually committing my changes to the repo here on Github the mirror finished successfully.

Hopefully the issue doesn't crop up again. Thanks @alexandremenif
