### ISSUE TITLE
Add user and password as credentials.

### ISSUE THREAD

**Issue by aadrian** [alexandremenif/gitbucket-mirror-plugin#6]
Hi,

Please add "user" and "password" as credentials too, since this is the most common feature most systems to push to will have.

Thank you.

**Comment by alexandremenif** [comment]
Hello. You can already add this kind of credentials in the URL. Did you try that? Or do you have something different in mind?

**Comment by aadrian** [comment]
Hi,

> You can already add this kind of credentials in the URL. Did you try that? Or do you have something different in mind?

Separate fields for the User and Password would be very helpful, so that the password does not show up in screenshots or in logs.

**Comment by alexandremenif** [comment]
Ok, I am going to work on this.

**Comment by alexandremenif** [comment]
If you want to have a look or make suggestions: PR #7 
I still need to fix a few things.

**Comment by aadrian** [comment]
@alexandremenif wow  ! 
https://github.com/alexandremenif/gitbucket-mirror-plugin/pull/7 looks great!

**Comment by alexandremenif** [comment]
What I have eventually implemented is a separate field for the password. I did not separate the username since SSH authentication requires it to be in the URL. It is available in the newly released [1.1.1](https://github.com/alexandremenif/gitbucket-mirror-plugin/releases/tag/1.1.1).

**Comment by aadrian** [comment]
@alexandremenif This is great! 
Thank you for the release!
